version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Download and install Google Chrome (latest)
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get --fix-broken --only-upgrade install google-chrome-stable

      - run:
          name: Install application dependencies
          command: npm install

      - run:
          name: Install server dependencies
          command: |
            cd server
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Create configuration file
          command: |
            cp server/config.json.template server/config.json
            sed -i "s/GOOGLE_MAPS_API_KEY/$GOOGLE_MAPS_API_KEY/i" server/config.json

      - run:
          name: Create application bundle file
          command: npm run bundle:test

      - run:
          name: Start test server
          command: |
            cd server
            npm start
          background: true

      - run:
          name: Wait for test server to be running
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:$PORT
            :

      - run:
          name: Run tests
          command: npm test
